name: vegan_liverpool
version: 0.0.1+11
publish_to: none
description: Food, Grocery delivery platform for Vegan products and food, with a built in wallet running on the Fuse network
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  animations: ^2.0.2
  another_flushbar: ^1.10.24
  auto_route: ^4.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  auto_size_text_field: ^2.0.0
  cached_network_image: ^3.2.0
  confetti: ^0.7.0
  dio: ^4.0.0
  equatable: ^2.0.3
  flex_color_scheme: ^5.0.1
  flutter_dotenv: ^5.0.0
  flutter_form_builder: ^7.1.0
  form_builder_extra_fields: ^8.1.0
  form_builder_validators: ^8.1.1
  flutter_localized_locales: ^2.0.2
  flutter_redux: ^0.10.0
  flutter_secure_storage: ^5.0.2
  flutter_sticky_header: ^0.6.0
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.3
  geocoding: ^2.0.1
  get_it: ^7.2.0
  google_maps_flutter: ^2.1.1
  google_api_headers: ^1.2.0
  injectable: ^1.5.3
  js: ^0.6.4
  logger: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  redux_logging: ^0.5.0
  redux_persist: ^0.9.0
  redux_thunk: ^0.4.0
  responsive_framework: ^0.2.0
  sentry_flutter: ^6.4.0
  uuid: ^3.0.6
  flutter:
    sdk: flutter
dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.8
  dependency_validator: ^3.1.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^2.1.1
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.3
  lint: ^1.5.3
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - environment/env
    - environment/.env_qa
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Europa
      fonts:
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 300
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 400
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 600
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 700
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 800
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 900
  uses-material-design: true
